site_name: " "

repo_url: https://github.com/andrewwkimm/koffee

repo_name: GitHub

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    # Light mode (for light systems)
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode (for dark systems)
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - cyclopts

nav:
  - koffee: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andrewwkimm/koffee

copyright: © koffee 2026