[project]
name = "koffee"
version = "0.1.0"
description = "A Korean<>English video file translator."
authors = [
    {name = "Kim, Andrew", email = "andrewkimka@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper>=1.0.3",
    "transformers>=4.39.3",
    "torch>=2.2.2",
    "accelerate>=0.29.3",
    "cyclopts>=3.24.0",
    "rich>=13.9.2",
    "pydantic>=2.9.2",
    "sentencepiece>=0.2.0",
    "sacremoses>=0.1.1",
]

[dependency-groups]
dev = [
    "coverage>=7.9.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.0",
    "behave>=1.2.6",
    "pre-commit>=4.3.0",
    "nox>=2025.10.14",
    "ty>=0.0.1a24",
]

[project.scripts]
koffee = "koffee.cli:main"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
include = ["src"]

[tool.ruff]
target-version = "py311"
line-length = 88
fix = true
unsafe-fixes = true

lint.select = [
    "B",    # bugbear
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "D",    # pydocstyle
    "E",    # pycodestyle
    "F",    # pyflakes
    "FLY",  # f-strings
    "I",    # isort
    "PERF", # performance
    "PL",   # pylint-like
    "PTH",  # pathlib
    "RUF",  # ruff-specific
    "SIM",  # simplify
    "UP",   # pyupgrade
]


lint.ignore = []

exclude = ["tests/data", ".venv", "build", "dist"]

[tool.ruff.lint.pydocstyle]
convention = "google"  # or "numpy" or "pep257"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
