[project]
name = "koffee"
version = "0.1.0"
description = "A Korean<>English video file translator."
authors = [
    {name = "Kim, Andrew", email = "andrewkimka@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper>=1.0.3",
    "transformers>=4.39.3",
    "ffmpeg-python>=0.2.0",
    "torch>=2.2.2",
    "accelerate>=0.29.3",
    "cyclopts>=2.9.9",
    "rich>=13.9.2",
    "pydantic>=2.9.2",
    "sentencepiece>=0.2.0",
    "sacremoses>=0.1.1",
]

[dependency-groups]
dev = [
    "coverage>=7.9.1",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.0",
    "hatch>=1.14.1",
    "behave>=1.2.6",
]

[project.scripts]
koffee = "koffee.cli:main"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
include = ["src"]

[tool.mypy]
files = ["src", "tests"]
cache_dir = "${HOME}/.mypy_cache"
ignore_errors = false
disallow_untyped_defs = true
exclude = 'features/steps/.*'

[tool.ruff]
target-version = "py311"
line-length = 88
fix = true
unsafe-fixes = true

lint.select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "B",   # bugbear
  "SIM", # simplify
  "D",   # pydocstyle
  "PL",  # pylint-like
  "C90", # mccabe
]

lint.ignore = []

exclude = ["tests/data", ".venv", "build", "dist"]

[tool.ruff.lint.pydocstyle]
convention = "google"  # or "numpy" or "pep257"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
